uchicago-library/library_website

public/templates/public/blocks/search_widget.html
public/templates/public/spaces_index_page.html
public/views.py
units/templates/units/browse_by_pulldowns.html

changed middle tab of search box to match sequence of search types below
Also removed building filtering to allow user to see all the main buildings from dropdown list in spaces pages.
Added some aria-labels to enhance search accessibility.

Middle Search tab re-titled, allow users to see all buildings in spaces

---

base/utils.py
library_website/settings/base.py
public/views.py

Addresses user complaint that you could not select another library while filtering by library in the spaces page, previously could only select 'All Libraries' and the currently selected library. However, this fix does not address filtering the buildings by feature, in other words a user can select a library and a feature that that library does not have producing a blank table.

Made all six libraries available for selection at all times

---

base/templates/base/public_base.html

“For” is not capitalized in accordance to CMOS 8.157: Principles of
headline-style capitalization

Nav change: Center for Digital Scholarship

---

public/templates/public/blocks/search_widget.html

Fixes #103 
Switches the databasefinder form action to the `/dbfinder` handle and modifies the input to work with the LibGuides A-Z list.

Modified the database search box to use the LibGuides A-Z list.

---

library_website/settings/base.py
library_website/settings/dev.py
results/views.py

Fixes #112.
- Pages in /restricted/ are now filtered out of search results.
- The test database was updated to include a restricted page and child page. 
- Config files were updated for production and dev to identify the restricted page.

Gets restricted pages out of search results and fixes issue #112.

---

base/tests.py
base/utils.py
group/models.py
intranetunits/models.py
library_website/settings/dev.py

Fixes #133.
- Updated the test database to include RESTRICTED pages
- Ran code through linter
- Added summaries and document link titles to the search_fields for GroupMeetingMinutesPage, GroupReportsPage and IntranetUnitsReportsPage models

133 index reports and meeting minutes metadata on loop

---

lib_news/models.py

Handled an attribute error while getting categories on a FakeQuerySet for LibNewsPages in PREVIEW mode. 
Fixes #171 
Instead of trying to display categories that are inaccessible in PREVIEW mode, we display simple text that should inform the editor as to what's going on and what they should do. This text is displayed in place of categories at the bottom of the news story.

Broken Preview on News Stories

---

base/static/base/css/lib_news.scss

Fixes #176 
Fixed max-width issue on full width images for news. This change is isolated to `section.news-stories`

Fixed max-width issue on full width images for news

---

staff/utils.py

Fixes #186
Ensure that only strings are being passed to the `_clean` function of `WagtailStaffReport`.

Out of Sync Staff Report Fails

---

base/templates/base/public_base.html

Fixes #196 
Updated the url field of the logo schema.org so that it will work with Django views in addition to Wagtail page objects.

Logo issues detected

---

lib_news/models.py

Fixes #209 
Adds the clearing of Redis cache for news site categories in the build_news_feed function. When a news site is published, the Redis cache for news categories is cleared, similar to what we do with the wagtail_cache.

Delayed display of news category changes to published pages

---

base/forms.py
base/management/commands/report_page_maintainers_and_editors.py
base/templates/base/page_owners_form.html
base/tests.py
base/wagtail_hooks.py

Fixes #215 
-  Adds departed, inactive staff to the page owner's report.
-  Switches the page owner's report to `StreamingHttpResponse` instead of `HttpResponse` to help with the Gateway timeout problem.

215 page owners report for departed staff

---

base/models.py

Fixes #228 
Adds a `live().public()` filter to the queryset in the `get_news` function of `base/models.py`.

Unpublished news stories that are scheduled to be published appear on kiosk pages

---

base/management/commands/update_site_data.py
base/tests.py

Fixes #256 
Adds a new `update_site_data` management command that can be used to update the site hostname and port number.
***Example uses***
`./manage.py update_site_data wwwdev -nh public-site`
`./manage.py update_site_data wwwdev -p 8888`
`./manage.py update_site_data wwwdev -nh public-site -p 8888`

Command for updating the site hostname

---

base/static/base/css/uclib.scss
base/templates/base/public_base.html

Closes #166
- Changes h2 into a p class
- Opted for no [aria role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles) in the banner as none meets the requirements/needs

Changed h2 to a class

---

alerts/utils.py
events/views.py
lib_collections/views.py
public/views.py
units/views.py

Added context variables to browse views for the display of alert banners, ran view code through linter and removed unused import statements.
Fixes issue #271
Adds banner alerts to the following views.
- https://www.lib.uchicago.edu/about/directory/?view=staff
- https://www.lib.uchicago.edu/collex/
- https://www.lib.uchicago.edu/about/news-events/events/
- https://www.lib.uchicago.edu/spaces/

Alert banners should display on browse views

---

public/models.py

Fixes issue #273.
Reverted the [changes introduced in a previous commit](https://github.com/uchicago-library/library_website/commit/c9dc6f6c4ed5331d40990f2f52007c60f914e483?diff=unified) that disabled select page types from being created under StandardPages. Only reverted changes in `public/models.py`.

Reverted changes that prevented needed page types under StandardPages

---

base/templates/base/minutes_and_reports_inner_table.html
group/models.py

Closes #255 
- Limited meeting minutes to only allow Wagtail pages
- Changed the minutes display table to a dictionary list
**Questions**
- Unsure if I should remove the else statements in the [meeting minutes model](https://github.com/uchicago-library/library_website/blob/master/group/models.py#L283) for determining between link and document files.
- Would love to switch the item link to be the date rather than the summary in the ["inner table"](https://github.com/uchicago-library/library_website/blob/master/base/templates/base/minutes_and_reports_inner_table.html#L6) but am not able to figure that one out.
- Also unsure why there is the `for item in items` line in this inner table since there is only one summary allowed per meeting minute item.

Limited minute types to wagtail page and changed table styling

---

units/tests.py
units/views.py

Fixes #293
- Fixed the incorrect display of the subject list that was incorrectly passing a `QuerySet` inside a `tuple` to the templates instead of passing the `QuerySet` directly.
-  Wrote a unit test so this doesn't happen again.
- Linted and autofixed the `units/tests.py` file

Subject dropdown display problem

---

base/models.py
public/templates/public/location_page.html

Fixes #294 
- Made the display of hours in the right sidebar optional for `LocationPages`. Previously `LocationPages` were setup to always display hours no matter what.

 Library spaces page hours widget bug

---

base/static/base/js/ga.public.js

Fixes #301
- Added javascript for doing event level tracking of reusable content widgets in the right sidebar.

Add event tracking to links in reusable content boxes

---

base/static/base/css/_variables.scss
base/static/base/css/global.scss
base/static/base/css/navigation.scss
base/static/base/css/sidebars.scss
base/static/base/css/uclib.scss

Closes #321
All color contrast min requirements are 4:5.1
- Changed nav link hover color contrast from 3.4:1 to 7.88:1
- Changed default link color contrast from 3:0 to 6.38:1
- Changed default hover color contrast from 3:1 to 5:21.1
- Added a change in text-decoration when in hover state (toggle between underline or none depending on where the link is)
- Added focus outline so we are not relying on browser styling for focus.

Changed default link colors and text-decoration

---

base/templates/base/includes/header.html

Verify against changes requested in #344 
Do not close issue; need to move pages in production
- Will be removing the "Alumni & Other Researchers" index page, so have updated links to reflect that
- Removed link for "Privileges at Other Libraries"
- Changed "Alumni & Other Researchers" to "Alumni"
- Added "Researchers from Other Colleges & Universities"
- Added "Other Visitors"

Updated borrow request nav links

---

base/static/base/css/uclib.scss

Closes #338 
- Moved button so it is in the same grid column as the profile photo
- Hide button on Law homepage

Removed button from Law

---

base/static/base/css/footer.scss
base/static/base/css/navigation.scss
base/templates/base/includes/footer.html
base/templates/base/includes/header.html
base/templates/base/public_base.html

Closes #322
- See Issue #322 for full detail of changes required
**Notes on Navigation**
- Properly nested the `ul` and `li` within each other
- Added `role="heading"` to subcategory `li` in ways that the role would only apply to the text itself (varies by type of dropdown menu
- `role="heading"` is paired with an `aria-level`
- Added `role="region"` and `aria-labelledby` to `ul` sections that are subcategories within mega dropdown items
**Issue with Hours**
The right nav drop-down version of the hours: `current_building_hours` not display any text in the DOM for a screen reader. The code loads as empty with no text. This means that screen readers do not know what the drop-down opens and the current building hours is hidden from them. This isn't an issue at the …

322 ada homepage and template easy fixes

---

lib_collections/views.py

Closes #351 351
- Removed `Cultural` from `Area & Cultural Studies`
- Grepped for other instances of `Cultural`

Removed Cultural from Area and Cultural Studies

---

base/static/base/css/loop/loop.scss
base/static/base/css/uclib.scss

Closes #374 
- Added media parameters so columsn only show up on horizontal tablet and above
- Fixed unsupported Safari flexbox item (gap)

Added media parameter

---

lib_news/models.py
lib_news/utils.py

Fixes #387
- Changes to the body fallback for, "short descriptions". If an excerpt is no longer present for a news story, short descriptions are created by truncating html from the news story body. This fallback will most likely never be used for an extended period of time in reality, since, this bug only appears to affect feature stories (that always have excerpts). In all likelihood this just protects the site while feature story author's are working on their stories. 
- Feature stories without excerpts no longer crash the news site homepage.
- The `get_first_feature_story` now only returns `live` published stories.
There are no migrations with this change set because the updates only affect a function that alters data after it leaves the database. It doesn't …

News stories without excerpts blow up the news homepage

---

library_website/settings/base.py
library_website/urls.py
search/views.py

Fixes #415 
- Adds a new view that takes a query and forwards it on as an ebooks search in the catalog.

Fix libguides ebook search

---

news/templates/news/news_page.html

Closes #413
To Loop news pages:
- Removed date suffixes (eg: -th, -nd) 
- Added comma after date
- Added year

Added year and comma, removed date suffixes

---

staff/test_integration.py

Fixes #417 
- Changed the XML DTD in tests to match the XML being returned by the University API. Tests should pass now.

Unit tests failing due to change in University directory xml

---

base/static/base/css/_variables.scss
base/static/base/css/sidebars.scss
base/static/base/css/uclib.scss
staff/templates/staff/staff_directory_listing.html
staff/templates/staff/staff_subjects.html
units/templates/units/unit_index_page.html

Closes #327
Please review original detailed ticket for problem code examples.
- Added descriptive `aria-label` to search box input
- Added `aria-label` to search box button
- Added hover and focus styling  to search button, directory toggle menu, and drop downs
- Added `aria-current="page"` to menu toggle (PLEASE DOUBLE CHECK)
- Added focus styling to search input
- Removed table from directory listing and restructured as divs
- Structurally placed staff image last and placed staff name in `h3` so this is properly read by a screen reader
- Added header tags and descriptive `aria-label` to subheadings per staff entry
- Added descriptive `aria-label` to sidebar Ask a Librarian links
**Question**
Please pay extra attention to the `{% if view == 'staff' …

Replaced staff directory tables with divs

---

base/static/base/js/library_website.js
public/templates/public/blocks/search_widget.html
public/utils.py
public/views.py

Fixes #434.
Previously, 'begins with' browse searches from the main search bar were being modified by Javascript so as to be compatible with VuFind's expectations.  But that Javascript wasn't updated to fit with what the DOI hijacker is doing.  This pull request has the DOI hijacker rather than the Javascript prep the home page search box to send those 'begins with' queries off to VuFind.

Move front page browse-search options from Javascript into Django

---

base/static/base/css/uclib-search.scss
base/static/base/css/uclib.scss
base/static/base/js/library_website.js
base/templates/base/public_base.html
lib_collections/templates/lib_collections/exhibit_page.html

Closes #449 
**Need Help on**
- Changed `#event-header` to `.event-header` for events sidebar module js.
- Code didn't seem to need this to be an ID, so changed to class to there aren't multiple duplicate ids when multiple events
- Unsure how to test: Could not verify this didn't break event module because local instance is fake and Nest is currently frozen.
- Added css to hide empty header tags
- Switch Sass function to darken citation text color (instead of lighten)
- Added if statement to `role-"list-item"` in carousel module
- Changed oveflow in search filter select item to `auto` instead of bootsrap default. Didn't seem to break anything in zoomed in view.

Fixed small ADA automation issues

---

base/static/base/css/_variables.scss
base/static/base/css/loop-navigation.css
base/static/base/css/loop.css
base/static/base/css/loop/_loop-variables.scss
base/static/base/css/loop/loop.scss
home/templates/home/home_page.html
intranethome/templates/intranethome/unit_page.html
library_website/settings/dev.py
library_website/templates/404.html
staff/templates/staff/staff_index_page.html

closes #450
- Added styling and removed tables from Loop staff directory
- Added correct base.html files for extending templates
**Possible issue uncovered**
- Able to view the Loop view of the staff directory at https://www.lib.uchicago.edu/staff/
- This view, along with the "No Permission" page come up as an ADA error for not having language assigned to it. Was not able to find the "No Permission" file.

Added styling to Loop staff directory

---

group/models.py
intranetunits/models.py

Closes #481 
- Removed name requirement of "Reports" from `GroupReportsIndexPage` and `IntranetUnitsReportsIndexPage`
- Removed name requirement of Year from `GroupReportsPage` and `IntranetUnitsReportsPage`

Removed name requirements for reports pages

---

base/static/base/css/_variables.scss
base/static/base/css/global.scss
base/static/base/css/loop-navigation.css
base/static/base/css/loop.css
base/static/base/css/loop/_loop-variables.scss
base/static/base/css/loop/loop.scss
base/static/base/css/sidebars.scss
base/static/base/css/uclib.scss
base/static/base/js/CGIMailForm.js
base/templates/base/intranet_base.html
base/templates/base/public_base.html
intranethome/templates/intranethome/intranet_home_page.html
library_website/templates/404.html
staff/templates/staff/staff_directory_listing.html
units/templates/units/unit_index_page.html

Closes #484 
**Not resolved**
- Not able to change Loop text from px to rem right now. Attached to `body` styling from Bootstrap CSS. Will effect entire site and needs more thought.
- Added screen-reader only h3 of staff name outside of divs
- Created h4 labels for About {{ staff name }} and Contact {{ staff name }}
- Made sidebar widgets with icons be entirely wrapped in link tag
- Resolved meta tag ADA issues on Loop templates
- Added links to 404 page (being [served on production](https://www.lib.uchicago.edu/collex/exhibits/adaptations-augie-march-novel-saul-bellow-play-david-auburn-production-directed-charles-newell-exhibition-special-collections-court-theatre/) with reference to links without linked text)
- Expanded `:empty` pseudo class to hid more empty …

Added ADA changes to directory and Loop

---

public/models.py
public/templates/public/blocks/staffpage_helppanel.html

Closes #491
- Decided to do a `def` only in `StaffPublicPage`
- Note on using `.instance`
- The base EditHandler class has access to the instance as long as the data is in the model.
- Value would not populate without `.instance` in the Wagtail admin although functions just fine if calling into a public-facing template.

Added help panel with direct link to Loop staff page

---

base/static/base/js/transformer-tabs.js
public/templates/public/blocks/search_widget.html

Fixes #479.
Add a little javascript to `transformer-tabs.js`, plus a couple extra `id`-s and `onchange` events to `search_widget.html`, to get the following effect:
- when the user types something in any of the search boxes on the main page, that something appears in all the search boxes
- when the user erases what's in any of the search boxes on the main page, they all go back to normal

479 retain search term when switching source

---

library_website/settings/base.py
staff/templatetags/staff_tags.py
units/models.py

Fixes #502
This fixes the staff browse problems related to page name changes.
- Moved the `BUILDINGS` constant in `units/models.py` into config
- Updated the `QUICK_NUMS` constant in config. Note: these changes had already been applied in `local.py` they were added here in `base.py` for consistency. 
- Assigned some staff to SCRC and SSA and preserved those changes in the test db fixtures
- Removed unused imports.

Staff browse returns nothing when searching SSA and SCRC

---

lib_collections/models.py
lib_collections/templates/lib_collections/collection_page.html

Fixes #505
This change puts the old links to view a digital collection back into the template, and adds a little conditional logic to suppress them if the collection page is one of the new ones that has been onboarded onto our new framework.  Finally, it adds a sample collection page to the fixtures, which a) got lost in the deploy shuffle and b)  will be useful for testing this new code.

Restore external links to digital collection landing page

---

base/templates/base/public_base.html

Closes #499
**Notes**
Difficult to shoehorn the ul / li structure into the Bootstrap carousel framework:
- Opted to move `listbox` to the already exisiting `ol`
- Swapped carousel item from `div` to `article` to fit typical ADA structure
- Need to revisit if we want to move away from a Boostrap option to something else. For now, resolves the SiteImprove error.

Changed list-box location

---

base/static/base/css/uclib.scss
base/templates/base/includes/header.html
base/templates/base/public_base.html
lib_collections/templates/lib_collections/collection_page.html
staff/templates/staff/staff_directory_listing.html

Closes #507 
- Updated SSA nav link to `Social Work` per Library name change
- Overrode Bootstrap focus CSS with code the Center for Digital Accessibility gave to us.
- Added screen reader only name label to Subject Guide links on Staff Browse to make links unique.
- Removed duplicate `id` in Digital Collections Browse template

ADA fixes and Social Work link update

---

lib_collections/tests.py
requirements.txt

Fixes #526
- Pegged `psycopg2` and `django-webpack-loader` to version numbers.
- Updated the html of a test to match what is in the template. The template changed as part of the ADA updates and the test needed to be altered to reflect that.

Fix unit tests for upgrade

---

base/static/base/css/global.scss
base/static/base/css/uclib-search.scss

Closes #525 
- Opted for `overflow: visible` as I've already tried auto and it did not resolve the SiteImprove error.
- Added dotted underline to hover and focus state in an attempt to silence link automation error
- Honestly unsure if either of these "fixes" will work to silence the automation errors, but I want to try.

Added link decoration and overflow visibility

---

base/templates/base/includes/footer.html
base/templates/base/includes/header.html
library_website/urls.py

Fixes #539
- Removed and added links in nav to match services for buildings reopening
- Rearranged footer links per Web Content Group discussion
- Unsuppressed Spaces browse

Nav and footer changes for buildings reopening

---

group/templates/group/group_reports_page.html

Fixes #546 .
- Moved for loop with dictionary list into the Report Page Index
- The structure was calling both child pages and uploaded links/docs specified from "Year" page. Moving `dl` to index seems to skip over this erroneous call. 
- Reviewed by EE, who reported the issue, so verify concern was resolved.

Added for loop directly in Reports Index template

---

base/static/base/css/collex-digital.scss
base/static/base/css/sidebars.scss
base/static/base/css/uclib.scss

Fixes #538
- Color change to required mark on forms (Can be see on local at `/about/directory/staff/jean-luc-picard/test-cgimail-form/`)
- Focus and hover changes to sidebar links. (Can be seen on local at `collex/collections/19th-century-maps-middle-east-north-africa-and-central-asia/`)
- Made temp load text for News images be black. Internet too fast to check; will see if successful in SiteImprove report next week)

Small color changes for ADA fixes

---

staff/utils.py

Fixes #553.
Uses `requests.exceptions.RequestException` to catch a broad class of exceptions due to timeouts, refused connections, etc.
- 
- 
-

get_token and libcal_id_by_email now catch all request exceptions

---

base/templates/base/includes/header.html

Closes #560
-Added "Book a Room" (rooms.lib.uchicago.edu/r/) to global navigation, under Remote & On-site Services|On-site Services
-Added "Spaces to Study" (https://www.lib.uchicago.edu/spaces/) to global navigation, under Remote & On-site Services|On-site Services

Added Fall links to global nav

---

base/static/base/css/loop.css
news/templates/news/news_excerpt.html
news/templatetags/news_tags.py
requirements.txt

Fixes #569 
- Fixes a Vagrant build bug by upgrading `DateTime`.
- Adds the display of `RichText` for news stories on the Loop homepage. `RichText` beyond anchors only displays for stories when the excerpt field has been filled out.
- Switches to built in Django template tags for truncation and away from a home brewed solution, simplifying the code.

Loop News Previews Should Display More Rich Text

---

public/models.py
public/utils.py

Fixes #574.
Adds a tiny amount of code to `public/models.py` and `public/utils.py` to throw the spaces locations into the search fields for `LocationPage`-s.

574 index features tags from library spaces

---

base/templates/base/public_base.html

Fixes #582.
The issue ended up being that the `public_base` template had *both* a reference to `uclib-print.scss` *and* a reference to `uclib-print.css`.  Perhaps this is because after the scss template was added to the 'compress' section, the old css include was accidentally left in.  In any event...

fix redundant inclusion of uclib-print.css in public/base template

---

item_servlet/tests.py
item_servlet/utils.py
item_servlet/views.py

Fixes #585 
- Allow bib level data to populate if items data is not present (was failing in select cases)
- Get items by barcode instead of filtering holdings > items by barcode.
**Testing Notes**:
- Fail case: https://catalog.lib.uchicago.edu/vufind/Record/1299992
- http://wwwdev:8000/item-servlet/?p=true&bib=1299992&barcode=088440577 should populate with item information, if it does not, empty the Wagtail cache in the admin.

Item servlet fails in some cases

---

Vagrantfile
lib_collections/tests.py
public/models.py
requirements.txt

Fixes #602 
- Fixes `django-static-precompiler` package in `requirements.txt`
- Gets unit tests passing again
- Fixes `--parallel` testing in the Vagrant environment
- Allocates more memory and cpu to Virtualbox
- New Vagrantfile and dev version of the site that runs on Ubuntu jammy and `Python 3.9`.
- Tweaks to `requirements.txt` for `Python 3.9`

Fix dev environment for new installs

---

ask_a_librarian/models.py
ask_a_librarian/templates/ask_a_librarian/ask_page.html
library_website/settings/base.py

Related to issue #628 
- Update LibAnswers domain to use the new syntax.
- Offloaded more to the config file and removed repetitive code.

LibAnswers phasing out old domain names

---

base/utils.py
requirements.txt
staff/management/commands/list_staff_wagtail.py
staff/wagtail_hooks.py
units/management/commands/list_units_wagtail.py
units/views.py

Fixes #647 
- Added a new `save_virtual_workbook` function to `base_utils.py` [(line 470)](https://github.com/uchicago-library/library_website/pull/648/files#diff-7d6137b6e6d905f7f7cd657953ba62d3ac6e351b31b5ea30b56cc70b8122dc28R470) to replace the one deprecated in `openpyxl`.
- Changed imports to use the new function instead of the old one.
- Pinned openpyxl to a semantic version: `openpyxl>=3.1.0,<3.2.0`.
- Linted files with black.

Vagrant builds fail because of openpyxl 

---

library_website/templates/404.html

Fixes #654 .
- added a fluid div in order to fix the smaller screen module problem
- decided that if we want to make this a 404 return instead of 200 that can be done in a different update

654 404 page left margin for smaller screens

---

results/templates/results/results.html
results/views.py

Fixes #649.
- adds a search bar underneath the search results
- the search bar has the previously searched term preloaded allowing the user to re-search based on previous search
- search bar is small on larger screen sizes

649 search bar in lib search results page

---

base/static/base/css/footer.scss
base/static/base/css/navigation.scss

Fixes #661 
- Changed the hover color of links in the main navigation to something with a sufficient color contrast.
- Changed the hover and focus colors of footer links to something with a sufficient color contrast.

Insufficient color contrast on some elements

---

base/static/base/css/lib_news.scss
base/static/base/css/uclib.scss
base/templates/base/blocks/duo_img.html
base/templates/base/blocks/img.html
base/templates/base/blocks/solo_img.html
base/templates/base/public_base.html
lib_news/templates/lib_news/lib_news_page.html

Fixes #663
See #663 for details.
- Removes bad `aria-labels` that were overriding good image alt text on various image blocks (duo, solo, and img). 
- Refactored html for the "more news" sections on kiosk and news article pages.
- Puts news category badges in an unordered list.
- Linted html templates.
**Seeing changes in dev**
This branch is currently checked out on `nest`.
```
git diff -w master
```
Make sure the updated CSS displays:
1. Run `./manage.py compress`
2. Restart the Django dev server.
3. Empty cache in the admin.

News related ADA issues

---

base/static/base/css/footer.scss
base/templates/base/includes/footer.html
base/templates/base/includes/header.html

Fixes #667
- Removed role and added aria-label to main navigation
- Removed region roles from subnavigation.
- Converted footer headings from `span`s to `h2`s.
- Linted
```
git diff -w master
```
Make sure the updated CSS displays:
1. Run `./manage.py compress`
2. Restart the Django dev server.
3. Empty cache in the admin.

More Header and Footer ADA Issues

---

base/templates/base/public_base.html
public/templates/public/blocks/featured_library_expert.html

Fixes #669
- Fixed alt text on featured library expert block
- Linted
In dev you'll need to add an image for the featured library expert on the homepage. You can do this by going to the librarian's loop staff page and uploading a new image.

Missing alt text on featured library expert

---

base/static/base/css/uclib.scss
lib_collections/templates/lib_collections/collecting_area_page.html
lib_collections/templates/lib_collections/collection_page.html
lib_collections/templates/lib_collections/collections_index_page.html
lib_collections/templates/lib_collections/exhibit_page.html
public/templates/public/location_page.html
public/templates/public/spaces_index_page.html
public/templates/public/staff_public_page.html
staff/templates/staff/staff_directory_listing.html
units/templates/units/unit_index_page.html

Fixes #671 
- Removed redundant headings in staff listing in directory and changed the heading structure here.
- SCSS changes related to the above.
- Removed alt text on _placeholder_ images in the staff directory.
- Removed alt text on other placeholder images throughout the site.
- Made "visit our locations" text in sidebar more accessible by moving it to an aria label.
- Linted all related templates and fixed invalid HTML errors.
```
git diff -w master
```
Make sure the updated CSS displays:
1. Run `./manage.py compress`
2. Restart the Django dev server.
3. Empty cache in the admin and from the shell both.

Staff directory ADA issues

---

static/css/admin.css

Fixes #676 
- Added admin css to override the bad rule.
`./manage.py compress` and restart dev server to test.

Move page button is invisible

---

base/static/base/css/lib_news.scss
base/templates/base/blocks/button.html
base/templates/base/includes/quicklinks.html
base/templates/base/public_base.html
intranethome/templates/intranethome/intranet_home_page.html
lib_collections/templates/lib_collections/collecting_area_page.html
lib_collections/templates/lib_collections/collection_object_page.html
lib_collections/templates/lib_collections/collection_page.html
lib_collections/templates/lib_collections/exhibit_page.html
lib_collections/templates/lib_collections/exhibit_results.html
lib_news/templates/lib_news/lib_news_page.html
public/templates/public/contacts_in_sidebar.html
public/templates/public/related_exhibits.html
public/templates/public/staff_public_page.html

Fixes #674
- Removed `role="button"` from `<a>` tags where links were _not_ functioning as buttons.
- Changed `<h3>`s to `<h2>`s in sidebar.
- Linted
`git diff -w master`

Sidebar ADA Issues

---

lib_news/tests.py
library_website/views.py

Fixes #692
- Make the page not found throw a 404 instead of a 200.

Page not found should return 404

---

base/templates/base/minutes_and_reports_inner_table.html
group/models.py
group/templates/group/group_reports_page.html

Fixes #694
- Graceful handling for reports pages when a report doesn't have a link.
- Linting
**Test**
- [Add a report to a GroupReportsPage in dev](http://loopdev:8000/groups/borg-victims-recovery/reports/) without assigning a link to the report.
- Go to the [GroupReportsPage ](http://loopdev:8000/groups/borg-victims-recovery/reports/2016/) and the [GroupReportsIndexPage](http://loopdev:8000/groups/borg-victims-recovery/reports/) in the browser. The summary will be displayed as plain text and the pages will function normally.

GroupReportsPages fail after adding a report without a link

---

.github/workflows/test.yml
Vagrantfile

Fixes #708
- Update the dev environment to Elasticsearch 7.
- Update to Elasticsearch 7 in GitHub Workflows.
- Change the way we install NodeJS to eliminate new warning.

 Fix dev environment issues

---

base/templates/base/blocks/staff_listing.html

Fixes #721
- Fixed bad image tag that was preventing thumbnails from displaying on the Staff Listing streamfield block.

Staff Listing Streamfield Does Not Display Images

---

lib_collections/templates/lib_collections/exhibit_results.html

Fixes #723 
- It wraps the content of the 'Current Exhibitions' in a div similar to the remaining widgets in the sidebar.

wrap current exhibitions in a widget div

---

Vagrantfile

Fixes #733 
- Switch from Python 3.9 to Python 3.10 in the dev environment.

Vagrant build fails because of python3.9 distutils

---

base/templates/base/blocks/staff_listing.html

Fixes #758
- Adds Libcal appointment scheduling button to the staff listing widget template.
Can be previewed here:
https://liblet.lib.uchicago.edu/research/scholar/about-us/

Enable Libcal integration from other views of Staff

---

base/static/base/css/loop.css
base/static/base/css/loop/loop.scss
base/static/base/css/sidebars.scss
base/templates/base/intranet_base.html

Fixes #753.
Fixes #754.
- create consistency in the content block width by changing the limit from the `p` rule to the general `.block-paragraph`.
- add `z-index` to the left sidebar so that its content doesn't get visually mixed with the footer.
- new logo's maroon has low contrast with loop's green so it was changed to the all-white logo.

753 inconsistet fonts and spacing on loop

---

base/templates/base/includes/header.html

Removes UBorrow link from header as the interface has been abandoned and the same service is now provided through Inter Library Loan.

remove uborrow

---

README.md
Vagrantfile

Fixes #769
- Ability to build the site without Elasticsearch.
- Ability to build the site without NodeJS
- Removed `Poetry` and `Fabric` dependencies in the build (these were never used).
To test run `ELASTICSEARCH=false NODEJS=false vagrant up` and put 
```
WAGTAILSEARCH_BACKENDS = {
'default': {
'BACKEND': 'wagtail.search.backends.database',
}
}
```
in your `local.py`.

Make it possible to spin up the dev site without Elasticsearch or NodeJS

---

item_servlet/utils.py

Partial solution for #763
- Makes the `item_servlet` use the new Folio auth endpoint. This is a basic implementation.
To test this you need to be on campus or using the University VPN. The `item_servlet` should populate with a healthy amount of data for the biob/barcode and the form should pre-populate with the author and title, etc.
- http://wwwdev:8000/item-servlet/?p=true&bib=9291257&barcode=109010396
- http://wwwdev:8000/about/directory/staff/jean-luc-picard/test-cgimail-form/?bib=9291257&barcode=109010396&subject=Ask+a+Librarian+Library+Catalog%3A+Divergent&referrer=https%3A%2F%2Fcatalog.lib.uchicago.edu%2Fvufind%2FRecord%2F9291257%3Fsid%3D65506850

Move to new Folio auth endpoint

---

group/models.py
group/templates/group/group_index_page.html

Fixes #798
- Remove the restriction on the number of `GroupIndexPages` that can exist (was previously 1).
- Allow `GroupIndexPages` to have `IntranetPlainPages` and other `GroupIndexPages` as children.
- Modifications to the code so that only `GroupPage` children under the `GroupIndexPage` are displayed, rather than all `GroupPages`.
- Suppression of the "Inactive Groups" heading when no inactive groups are present.

Move Inactive Groups to a Separate Page

---

group/models.py

Fixes #802 
- Fixed bug that was causing Loop groups and subgroups to be inverted.

Inverted Groups

---

README.md

Title: Add New Venv Info and Wagtail Cache Command to README
Fixes #810
Summary
Updated the README to reflect the current virtualenv name and added information about the Wagtail cache command.
- Changed virtualenv name from `venv3.9` to `venv` in the Pushing to Production and Pushing a branch to Nest sections
- Added the `./manage.py clear_wagtail_cache` command to the Caching Issues section
Testing:
Reviewer can verify that the README now correctly references the `venv` virtualenv name and includes the Wagtail cache command.

Add New Venv Info and Wagtail Cache Command to README

---

base/templates/base/intranet_base.html

Fixes #815
Summary
Removed the Forms link from the Loop main navigation as requested.
- Removed the HTML list item containing the link to /forms/ from the main navigation in intranet_base.html
Testing:
Navigate to the Loop intranet site and verify that the Forms link no longer appears in the main navigation bar.

Remove Forms Link from Loop Main Navigation

---

findingaids/models.py
findingaids/templates/findingaids/finding_aids_page.html
library_website/settings/base.py
requirements-dev.txt

Fixes #817.
This PR avoids the in-browser memory leak by:
- adding an "all" button to the alphabetic browse links, which takes the user to a paginated listing of all finding aids pages
- retaining non-paginated listing of all title alphabetic browses
- retaining non-paginated listings of topic and digital-content-related browses
- retaining the old behavior in the face of searches
In addition, it simplifies the conditional logic in the `findingaids/templates/findingaids/finding_aids_page.html` template into something more linear, hopefully making the template easier to maintain in the long run.

817 fix finding aids crash when logged in

---

.gitignore
lib_collections/models.py
lib_collections/tests.py

Fixes #819
Summary
Fixed the exhibit search functionality by adding a FilterField for the web_exhibit field to enable proper filtering in search results.
- Added index.FilterField('web_exhibit') to ExhibitPage.search_fields (line 2139 in models.py)
- Created TestExhibitFiltering class with unit tests to verify filtering functionality works correctly
- Removed fixtures from tests to improve test execution time
- Added .vscode to .gitignore
Note: This PR includes significant linting changes in lib_collections/models.py and lib_collections/tests.py. The functional changes are adding the FilterField on line 2139 of models.py and adding the new TestExhibitFiltering test class in tests.py. All changes in models.py besides the FilterField addition are formatting improvements.
Testing:
1. Run the …

Cannot Limit to Web Exhibits When Searching

---

base/models.py
base/templates/base/public_base.html
base/views.py
events/utils.py

Fixes #824
**Summary**
Fixed event filtering logic to properly display future multi-day events like exhibitions, and improved URL handling in the json-events endpoint. Also modernized code with date format constants and better error handling.
- Modified expand_multiday_entries to include events with future end dates
- Fixed URL decoding in json_events view
- Added date format constants and improved code quality
**Testing**:
The code is already deployed on `nest` (https://liblet.lib.uchicago.edu/) and can be tested in several ways:
1. Visit https://liblet.lib.uchicago.edu/ and https://liblet.lib.uchicago.edu/crerar/ where the "[Seeing Connections: The Art of Richard Penn](https://events.uchicago.edu/event/247878-seeing-connections-the-art-of-richard-penn)" exhibit should now appear in the …

Fix events feed to properly display multi-day events

---

library_website/settings/base.py
library_website/urls.py
requirements.txt

Title: Add Cloudflare Turnstile protection against distributed AI harvesting bots
Fixes #827
Summary
Integrates Cloudflare Turnstile protection to defend against distributed AI harvesting bots that attack with unique IPs on every request.
- Added django-turnstile-site-protect package to requirements.txt
- Configured Turnstile middleware and settings in Django
- Set up appropriate exclusions for admin pages, static files, and authenticated sections
- Implemented non-interactive mode for minimal user impact
- Configured session timeout settings
Testing:
This can be deployed and tested on https://liblet.lib.uchicago.edu/ () to verify functionality before merging to production.

Add Cloudflare Turnstile protection against distributed AI harvesting bots

---

library_website/settings/base.py

Fixes #829
Summary
Password-protected pages in Wagtail were not working after the Cloudflare Turnstile implementation. When users entered the password, nothing happened.
- Added  to TURNSTILE_EXCLUDED_PATHS to exclude Wagtail's utility endpoints from Turnstile verification
- This allows the /_util/authenticate_with_password/ endpoint to function properly
Testing:
1. Clear the wagtail-cache before testing (either in the admin or with )
2. Visit a password-protected page such as https://www.lib.uchicago.edu/collex/exhibits/binding-energy/
3. Enter the password and verify that the page loads correctly

Fix Wagtail password protection by excluding /_util/ paths from Turnstile

---

base/static/base/js/jquery.track-everything.js
base/templates/base/public_base.html
public/templates/public/blocks/search_widget.html

Fixes #826 
- Completely rewrites the track everything script.
- It can now submit events to GA4.
- It can now track all clicks on VuFind. (vufind needs to include this script https://github.com/uchicago-library/vufind/tree/add-script-for-click-tracking)
- Code is much cleaner.
- Includes a debouncing function that was not working, but I left it there anyway.
- It still accepts specific html encoded event parameters, but it has a bunch of logic to track other cases.
- Improves homepage search widget tab tracking.

826 update click tracking to ga4

---

base/templates/base/public_base.html

Fixes #840
This PR fixes an issue where appointment buttons on CDS staff pages (e.g., /research/scholar/about-us/) were not working. The problem was caused by the  script only being loaded on the homepage due to a conditional check.
- Removed conditional check that was preventing the appointment button initialization script from loading on non-homepage pages
- Ensured the script loads on all pages where appointment buttons might appear
1. Navigate to a CDS staff page (e.g., /research/scholar/about-us/)
2. Verify that clicking an appointment button opens the scheduling modal
3. Verify that appointment buttons still work on the directory page

Fix appointment buttons on CDS staff pages

---

events/utils.py

Title: Fix event display issue with inconsistent GUIDs between feeds
Fixes #845
Summary
Modified the event filtering logic to handle inconsistent GUID formats between University and TTRSS feeds.
- Added slug-based matching to handle events with different URL formats
- Fixed comparison between University feed's 'link' field and TTRSS feed's 'guid' field
- Implemented fallback matching for events with numeric IDs in URLs
Testing:
1. Verify that events with multiple tags (e.g., 'library' and 'science') now appear on all relevant kiosk pages
2. Check that the 'Reg Reads Book Club Summer Meeting' event appears on both the library homepage and crerar page

Fix event display issue with inconsistent GUIDs between feeds

---

library_website/settings/production.py

Fixes #852
Summary
Adds CSRF_COOKIE_SECURE setting to production environment to fix Firefox CSRF verification failures on homepage search forms. Firefox requires the Secure flag on CSRF cookies for HTTPS sites.
- Add CSRF_COOKIE_SECURE = True to production.py
Testing:
This branch is checked out on nest and can be tested there.

Firefox CSRF verification failure on homepage search forms

---

lib_collections/tests.py
lib_news/tests.py
requirements.txt

Fixes #859 
**Changes in this request**:
- Upgrades to `Django 5.2.6` 
- Upgrades to `Wagtail 7.0.3`
- https://docs.djangoproject.com/en/5.2/releases/5.1/
- https://docs.djangoproject.com/en/5.2/releases/5.2/
- https://docs.wagtail.org/en/stable/releases/6.2.html
- https://docs.wagtail.org/en/stable/releases/6.3.html
- https://docs.wagtail.org/en/stable/releases/6.4.html
- https://docs.wagtail.org/en/stable/releases/7.0.html
This can be [previewed on liblet](https://liblet.lib.uchicago.edu/).

Upgrade Wagtail and Django
