- base/static/base/css/uclib.scss
- events/templates/events/events_index_page.html
Added ADA features to table and changed the month view styling.
> Updated to Month View in Event Calendar Listing

- base/static/base/css/navigation.scss
- base/templates/base/public_base.html
- public/templates/public/staff_public_page.html
To reflect UChicago changes & VuFind update.
> Changes to My Account on Wagtail

- base/static/base/css/_media.scss
- base/static/base/css/third-party/azList.css
- base/static/base/css/uclib_print.scss
- base/templates/base/public_base.html
Separated Media Queries from Print Styles. Added CSS for third party
A-Z styling.
> Media Queries Update and A-Z styling

- base/static/base/css/_media.scss
- base/static/base/css/_variables.scss
- base/static/base/css/global.scss
- base/static/base/css/navigation.scss
- base/static/base/css/sidebars.scss
- base/static/base/css/uclib-search.scss
- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
- lib_collections/templates/lib_collections/collections_index_page.html
> Hours for Mobile fix & ADA Menu changes

- lib_collections/templatetags/lib_collections_tags.py
- lib_collections/views.py
- library_website/settings/base.py
- public/views.py
- requirements.txt
> Attempting to make successful merge into lib_website

- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
- lib_collections/templates/lib_collections/collections_index_page.html
- lib_collections/views.py
- subjects/models.py
Adds a "View Collecting Page" link to Subject Browse and hides breadcrumbs from Reg Homepage
> Coll area browse view

- base/models.py
- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
Originally was going to add data models for the Reg Homepage, but decided to push this out separately.
> Global Nav and Carousel Styling

- conferences/models.py
- library_website/templates/404.html
Allows conferences to be nested and is a patch to #39
> Custom 404

- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
Related HTML on Wagtail that needs to be published when this is pushed to production. Please alert me when this is pushed so we can coordinate publishing the related page updates. Closes #22
> Update to Mobile Hours Widget from Springshare

- base/static/base/css/uclib.scss
- intranethome/templates/intranethome/intranet_home_page.html
Includes small public site CSS tweaks and updates to Loop sidebar
> Directory width and Loop sidebar

- ask_a_librarian/templates/ask_a_librarian/ask_page.html
- base/static/base/css/sidebars.scss
- base/static/base/css/uclib.scss
- intranethome/templates/intranethome/intranet_home_page.html
- public/templates/public/blocks/search_widget.html
- units/templates/units/unit_index_page.html
- Fixed sidebar issues  on Ask a Librarian
- Changes "Ejournals" in search bar to be consistent with style guide
- Fixed broken webcams link in Loop
> Ask+ejournals

- base/static/base/css/loop-navigation.css
- base/static/base/css/loop-styles.css
- base/static/base/css/loop.css
- base/static/base/css/loop/_loop-variables.scss
- base/static/base/css/loop/loop-navigation.scss
- base/static/base/css/loop/loop.scss
- base/static/base/css/uclib.scss
- base/templates/base/intranet_base.html
- base/templates/base/intranet_index_page.html
- base/templates/base/intranet_plain_page.html
- gulpfile.js
- intranethome/templates/intranethome/intranet_home_page.html
- search/templates/search/loop_search.html
- staff/templates/staff/staff_page.html
Includes new header colors and staff page layout. Included ADA labels.
Kathy still needs to:
Update TOC page layout.
John still needs to:
Change staff link on staff directory to direct to Loop staff page instead of public staff page
> Typography and Search Styling Updates

- base/templates/base/includes/header.html
- staff/templates/staff/staff_directory_listing.html
- staff/templates/staff/staff_index_page.html
Changed nav link to "Proxy & Off-Campus Access" as well as added ADA code to Staff Directory table.
> Changed Global nav for Proxy page

- base/templates/base/includes/header.html
Step 1 of #92
Kicks off the migration of Book a Room.
> #92 Updated Book a Room link in header

- .gitignore
- README.md
- Vagrantfile
- search/templatetags/core_search_tags.py
Fixes #94 
Adds a Vagrantfile and fixes a bug with search that was breaking on the dev version of the database.
> 94 create a vagrant image

- base/templates/base/includes/footer.html
> Added Library Twitter link to footer

- requirements.txt
Fixes #110 and patches the requests related security vulnerability.
Upgraded the requests package to version 2.20.0.
> Upgraded the requests package.

- base/templates/base/includes/footer.html
Fixes #117 
Updated links in Law footer to Facebook, Twitter, and Instagram
> Updated links to Law social media accounts

- ask_a_librarian/templates/ask_a_librarian/ask_page.html
> Filtered out friendly names for the Ask Chat buttons on Science and SSA

- base/forms.py
- base/management/commands/report_page_maintainers_and_editors.py
- base/templates/base/page_owners_form.html
- base/tests.py
- base/wagtail_hooks.py
> 123 wagtail page owner reports

- base/management/commands/report_page_maintainers_and_editors.py
- base/tests.py
- base/utils.py
- base/wagtail_hooks.py
Fixes #140 
Optimizations to increase speed.
> 140 performance with page owners report after server upgrade

- base/static/base/css/uclib.scss
> Fixed image to be responsive within carousel container

- .travis.yml
- ask_a_librarian/tests.py
- base/models.py
- base/tests.py
- conferences/models.py
- group/models.py
- intranetunits/models.py
- public/models.py
- requirements.txt
- units/models.py
Fixes #148
Upgrades to Django 2.2.1 and Wagtail 2.5.1. Upgrades additional dependencies and compatibility modifications to code.
> Upgrade to Wagtail 2.5.1

- lib_collections/models.py
- lib_collections/templates/lib_collections/collection_page.html
- lib_collections/templates/lib_collections/exhibit_page.html
Added a fix for unit_contact on exhibit and collection pages.
Fixes #151.
Adds unit_contact display information to ExhibitPages and fixes the display on CollectionPages. Additional code cleanup.
> Fix Unit Contact on Exhibit and Collection Pages

- lib_collections/templates/lib_collections/exhibit_page.html
Fixes #150 
Edits to the template so that the header and structural html only display if data is present.
> Fixed the display of exhibit details in the right sidebar.

- public/static/public/css/webforms.scss
- public/templates/public/public_raw_html_page.html
Fixes #154 
- Added webform.scss
- Linked Sass to raw html template
All other form changes are within production Wagtail.
> Added web form styles and linked to html template

- ask_a_librarian/templates/ask_a_librarian/ask_page.html
- ask_a_librarian/utils.py
- library_website/settings/base.py
Fixes #145
- Replaced LibraryH3lp chat widgets with LibChat widgets
- Updated chat status API calls to use LibChat
> Replaced LibraryH3lp chat widgets with LibChat widgets and updated the

- intranethome/templates/intranethome/intranet_home_page.html
Closes #157 
- Added link to LibApps login to Loop homepage sidebar
- Merged "Interests" and "Resources" together on Loop homepage sidebar
- Alpha ordered the links in Loop homepage sidebar
> Added LibApps and changed homepage sidebar links

- base/templates/base/includes/footer.html
Closes #159
- Added "Library Policies" to footer
- New link goes to main Policies parent page: https://www.lib.uchicago.edu/about/thelibrary/policies/
> Added Policies link

- lib_news/templates/lib_news/lib_news_top_nav.html
> Added a trailing / to links in the Browse by Category dropdpwn

- base/static/base/css/lib_news.scss
- lib_news/templates/lib_news/lib_news_page.html
Fixes #180 
- `ul` styled same as `p`
- Removed time from byline
- Added comma after date in byline
> Time removed from byline and ul styling updated.

- lib_news/templates/lib_news/lib_news_page.html
Fixes #180 .
- Added comma after date
> Added comma after year

- base/static/base/css/uclib.scss
Fixes #183 
- Carousel width limitation extended to include mobile
> Carousel width in mobile fixed

- base/static/base/css/sidebars.scss
- base/templates/base/includes/quicklinks.html
- base/templates/base/public_base.html
- lib_collections/models.py
- lib_news/templates/lib_news/lib_news_page.html
Addresses some issues in #173 
- Changed right sidebar `h2` to `h3`
- Update styling so headers look the same as before
> Updated right sidebar headers for ADA and consistency

- base/static/base/css/global.scss
- base/static/base/css/sidebars.scss
- base/static/base/css/uclib.scss
- lib_news/templates/lib_news/lib_news_page.html
Fixes #193 
Also included small fixes...
- Added padding to sidebar items (no ticket)
- Added “clear” to bottom of news stories ( closes #190 )
- Added default styling for solo/duo images (closes #193 )
> Added padding to sidebar items, added “clear” to bottom of news

- base/templates/base/blocks/agenda.html
Fixes #194
- 24 hour changed to 12 hours for front end display
- Admin interface still has time chooser in 24 hour
> Updated time to display in 12hr

- lib_news/templates/lib_news/lib_news_page.html
Fixes #197 
- Added escapejs to schema.org fields.
> Unparsable structured data

- base/views.py
- events/utils.py
- events/views.py
- library_website/settings/base.py
Fixes #207 
Updated events feed code to work with HTTPS.
> Updated events feed code to work with HTTPS.

- base/static/base/css/footer.scss
- public/templates/public/blocks/search_widget.html
Fixes #219 
- Boosted contrast in footer in fallback background-color
- Added labels to search input and dropdown
> Small ADA fixes for false-positive issues

- base/static/base/css/_variables.scss
- base/static/base/css/lib_news.scss
- base/static/base/css/navigation.scss
- base/templates/base/public_base.html
- lib_collections/templates/lib_collections/exhibit_page.html
- lib_news/templates/lib_news/lib_news_index_page.html
- lib_news/templates/lib_news/lib_news_page.html
- lib_news/templates/lib_news/lib_news_top_nav.html
Fixes #222 
- Added alt text to SCRC exhibits using Image's title
- Bumped color contrasts to meet AAA requirements
- Added aria lables to buttons and secondary navs
> Added aria labels and bumped background colors to AAA contrast ratings.

- events/views.py
- library_website/settings/base.py
Fixes #224 
Moved the TTRSS url into config and cleaned up the code a little.
> Moved TTRSS feed url into config and ran code through a linter.

- units/templates/units/unit_index_page.html
> Bad link on staff directory

- base/templates/base/includes/header.html
> Changed labeling of Scholarly Communication nav section

- base/templates/base/includes/header.html
> Fixed broken link for the CDS page in main nav

- base/static/base/css/loop/loop.scss
- intranethome/templates/intranethome/intranet_home_page.html
Part of Issue #267 which I will keep open for future update needs.
- Added alert link to Loop quicklinks
> Added alert link to Loop quicklinks

- public/templates/public/blocks/search_widget.html
Closes #282
- Commented out ILL links
- Enlarged e-materials text with in-line styling
All changes should be reverted after students return to campus.
> Commented out ILL links and enlarged ematerials text

- base/static/base/css/base.scss
- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
Closes #285
- Changed inline to inline-block in banner
- Wrapped alert link in a span to control styling better
- Also did a style fix for the reusable widget
> Changed inline to inline-block in banner

- base/templates/base/includes/css.html
- base/templates/base/includes/js.html
- base/views.py
- library_website/settings/base.py
Fixes issue #299.
- Adds footer styling to the external include css endpoint
- Fixes the Fontawesome cdn in the external include css endpoint 
- Fixes broken javascript paths in the js endpoint
- Adds forms to to the CORS configuration
> Improvements for the external include api

- .travis.yml
- library_website/settings/base.py
- staff/utils.py
Fixes #306 
- Fixes Travis CI build
- Upgrades Travis CI Build to Python 3.7
- Adds empty config to `base.py` for libcal stuff
- Adds error handling for empty config
> Fix Travis CI

- base/templates/base/public_base.html
- public/templates/public/blocks/featured_library_expert.html
Closes #331
- Changed label "Featured Library Expert” to "Contact Your Library Expert"
- Changed “Consult [librarian name] on” to “Ask [librarian name] about”.
**New Ticket**
- Unable to figure out adding scheduler button. Made new ticket for Matt (#338)
> Changed featured widget labels

- group/models.py
- intranethome/models.py
Closes #355 
- Added `'base.IntranetIndexPage'` to two `subpage_type`
> Added Intranet Index page to some subpage types

- public/models.py
Fixes #358 
- Adds the CGIMail Form widget to `PublicRawHTMLPages`.
> Added the CGIMail form widget to PublicRawHTMLPages.

- base/static/base/css/loop.css
- base/static/base/css/loop/loop.scss
Closes #374
- Added  styling to visually support columns in Loop
> Added columns styling to Loop

- base/static/base/css/loop.css
Fixes Kathy forgetting that Loop styling needs to be manually compressed.
> Updated Loop CSS

- base/templates/base/includes/header.html
Closes #377 
- Changed Nav link for Trial
- Other changes need to be done in Guides and Wagtail admin
> Updated nav link

- search/views.py
Fixes #386 
- Moved the `loop_homepage` variable definition to the top of the view and added the permissions checking code we use on normal loop pages.
- Linted the file
Linting makes it look like many changes were made, however, all I really did is move the `loop_homepage` variable up and add this blurb:
```
if not has_permission(request.user, get_required_groups(loop_homepage)):
return redirect_users_without_permissions(
loop_homepage, request, None, None
)
```
>  The loop-search view is accessible from the public domain

- base/views.py
Fixes #388
- Better handling for when no libcal id is present. This prevents errors from being logged unnecessarily.
- Helper method for getting libcal IDs
- Minor linting changes (isort of imports)
>  Internal server error json-hours

- base/static/base/css/lib_news.scss
Closes #401
- Changed font size to rem rather than em
> Changed font size to rem

- library_website/urls.py
Fixes #405 
- Commented out routing for spaces browse in urls.py.
> Suppress Spaces Browse

- requirements.txt
Fixes #400 
- Major version upgrade of Pillow
- Minor version upgrades of Wagtail and Django
- Patches security vulnerabilities
> Upgrade Python dependencies to patch security vulnerabilities

- base/templates/base/public_base.html
> Corrected if statement ending

- base/templates/base/public_base.html
- public/models.py
Fixes #407 
- New boolean for testing widget existence
> Hot fix for item icons displaying in sidebar when not filled out.

- base/static/base/css/_variables.scss
- base/static/base/css/sidebars.scss
- base/templates/base/includes/header.html
Closes #410
- Updated link for Returns in global nav
- Fixed padding issue with icons in sidebars
> Updated returns in nav

- base/templates/base/includes/header.html
(Re) Closes #410 
- Added link to LibCal reserve a seat page.
> Added seat reserve link

- findingaids/models.py
Fixes #419 
- Added handling for empty subjects.
> Broken Finding Aids Browse

- base/static/base/css/uclib.scss
Closes #422 
- Added media queries to carousel image
- Added height parameter to carousel image for mobile only
- Made carousel image fit to cover in mobile only
> Changed carousel image sizing for mobile only

- public/templates/public/blocks/search_widget.html
Fixes #425 
- Restored WorldCat link in search box.
> Restore WorldCat link in front page search box

- base/templates/base/includes/header.html
Closes #427
- Added Printing to On-Site Services
- Changed About > Visiting to link to the Visiting page in Access
- Changed "Reserve a Seat" to "Book a Seat"
> Added printing to main nav

- base/templates/base/page_owners_form.html
- news/templates/news/loop_news_notifications.html
- news/templates/news/loop_news_notifications_thanks.html
- staff/templates/staff/staff_reporting_form.html
- staff/templates/staff/staff_reporting_form_thank_you.html
- units/templates/units/unit_reporting_form.html
- units/templates/units/unit_reporting_form_thank_you.html
Fixes #430 
- Replaced deprecated calls to `staticfiles` with `static`
> Broken Admin Report Pages

- base/templates/base/blocks/duo_img.html
- base/templates/base/includes/footer.html
Closes #437
- Added alt text to duo images
- Changed `header` to aria correct term `heading` in footer list
> Added alt text to duo image

- base/templates/base/includes/header.html
- Updated Book a Room link to  https://rooms.lib.uchicago.edu/r
- Leaving issue open because I need to make changes to Springshare navs too
> Updated rooms nav link

- base/static/base/css/footer.scss
- base/templates/base/includes/footer.html
Closes #445
- Added the UChicago accessibility link required
- Added underline to foot links for ADA compliance
> Added Univeristy ADA link

- base/static/base/css/footer.scss
- base/templates/base/blocks/image_link.html
- base/templates/base/includes/footer.html
- base/templates/base/intranet_base.html
- base/templates/base/public_base.html
- lib_news/templates/lib_news/lib_news_top_nav.html
Closes #448
- Added `aria-labelledby` in a new span for Footer columns link headlines
- Added `lang="en"` to htlm tag in Intranet base template
- Changed `aria-label` in secondary Library news nav for language compliance
- Added alt text in code for Linked Image Streamfield
- Added empty hard-wired alt text for hero images
> Template changes for SiteImprove ADA

- public/templates/public/blocks/related_exhibit.html
Closes #452
- Included closing date into if statement for opening and closing date.
> Added if statement to closing date

- group/models.py
closes#455
**Changes in this request** 
- added group page as subpage type to group page
> Added group page as subpage type

- base/static/base/css/sidebars.scss
- lib_collections/static/lib_collections/css/collex.scss
- lib_collections/templates/includes/sidebar.html
- lib_collections/templates/lib_collections/collections_index_page.html
- lib_collections/templates/lib_collections/exhibit_page.html
- lib_collections/templates/lib_collections/exhibit_results.html
- lib_collections/templates/lib_collections/header_collections.html
- lib_collections/templates/lib_collections/header_exhibits.html
- lib_collections/templates/lib_collections/header_subject.html
Closes #325
- Changed collex sidebar headers to match standard pages (`h3` and `h4`)
- Added alt text to SCRC exhibit sub-footer image
- Added variable around location link in Exhibit browse
- Added `collex.scss` file back; accidentally deleted by auto-merge from previous merge.
- Fixed aria label typos
> Small ADA fixes and added collex.scss back

- base/static/base/css/uclib-search.scss
- base/static/base/css/uclib.scss
- base/templates/base/includes/footer.html
- base/templates/base/includes/header.html
Closes #513 
No rush; push to production date is Monday the 14th
*Changes in this request*
- Added bold styling to some link hover effects
- Separated link focus styling to appease a SiteImprove error
- Added more obvious focus styling to some link elements
- Removed auto overflow on search button as it did not silence the error on SiteImprove as hoped
- Snuck in SSA link and name change updates
> SiteImprove Fixes and SSA footer change

- library_website/settings/base.py
Fixes #541 
- Update CGIMail form config to use a site relative path instead of an absolute URL endpoint.
>  CGIMail error in Loop 

- intranetunits/models.py
Fixes #546
- Applied changes to the Department report page model rather than the group report page model
- Did not specific page type as model includes `subpage_types = ['intranetunits.IntranetUnitsReportsPage']`
> Fixed year pages issue in Dept

- base/utils.py
- requirements.txt
Fixes #558
- Removes unused `feedparser` dependency in `requirements.txt`.
- Removes unused imports in `base/utils.py`.
>   Feedparser build error in Vagrant

- library_website/settings/base.py
- requirements.txt
Fixes #571
- Upgrade to Elasticsearch 6
> Upgrade Elasticsearch to 6

- intranetunits/models.py
Fixes #589 
- Add handling for when no job title is present.
> Fatal error on IntranetUnitsPage

- base/static/base/js/library_website.js
- events/utils.py
Fixes #596 
- Updates to the XML parsing and Javascript to reflect the new output from LiveWhale.
> Broken events widget after upgrade to LiveWhale

- base/templates/base/includes/header.html
Fixes #604 
Updating the Nav Bar of the Library Website following the notations of following spreadsheet: https://docs.google.com/spreadsheets/d/1MsUNt_rSbP3kZucNFrCUlwWO8RQZiGtmpOfnVxaEOsA/edit?usp=sharing
Note: I did not add "UChicago Alumni" under Visit & Study per David Bottorf's comment in the spreadsheet linked above
> 604 update global nav

- package-lock.json
- package.json
> Additional security patches

- base/utils.py
- group/models.py
Fixes #625
- Add missing import.
- Change the way linked documents are tested for.
> Problem uploading meeting minutes

- intranethome/templates/intranethome/intranet_home_page.html
Fixes #617 
- Basically just changed the link
> changed the link

- base/templates/base/public_base.html
Fixes #643 
- New Google Analytics tracking code.
> Add Google Analytics 4 tracker to Wagtail

- base/templates/base/intranet_base.html
Fixes #652
- Adds Google Analytics to the intranet site.
> Add new Google Analytics tag to Loop

- base/static/base/js/transformer-tabs.js
- public/templates/public/blocks/search_widget.html
- staff/templates/staff/staff_index_page.html
Fixes #659 
- Replaces bad aria labels with meaningful text.
- Lints templates.
```
git diff -w master
```
> Search inputs are missing accessible text

- base/static/base/css/uclib-search.scss
- base/static/base/js/transformer-tabs.js
- public/templates/public/blocks/search_widget.html
Fixes #681
- Fixed heading structure.
- Enabled tab related aria roles to communicate the tab state to screen readers.
- Added keyboard functionality to tabs.
**Related documentation**
- https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
- https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
> Search tabs structure

- base/models.py
- base/tests.py
Fixes #696 
- Added handling for empty spreadsheets that might be uploaded.
- Added handling for a spreadsheet that might be "stealth deleted" from the documents screen.
- Added unit tests for the above scenarios.
> Empty Spreadsheets Should Be Handled Better

- intranethome/static/intranethome/css/style.css
- intranethome/static/intranethome/js/accordion.js
- intranethome/templates/intranethome/mail_aliases.html
- intranethome/tests.py
- intranethome/views.py
- library_website/settings/base.py
- library_website/urls.py
Fixes #658 
**Changes in this request for Mail Aliases Page**
- Created a new branch based off of master to deal with the accidental merge
- Also fixes the issues that were listed in the previous PR
> new mail aliases pr to fix the merge and requested changes

- base/templates/base/includes/header.html
Fixes #711 
- changed the 'book a room' link from https://rooms.lib.uchicago.edu/r
- to https://rooms.lib.uchicago.edu/r/search/seats#s-lc-public-pt
> Update book a room link

- README.md
- base/templates/base/includes/header.html
- added a more direct link in the menu nav to the DEI page
- updated README instructions according to Brad
> Surface DEI link in menu

- events/utils.py
Fixes #719 
- Updated xml parsing to match the University's new structure for the LiveWhale feed.
- Removed an unused import.
> Calendar Feed Down

- base/static/base/css/_variables.scss
- base/static/base/css/navigation.scss
- base/static/base/css/uclib.scss
Fixes #731 
- updates news category colors
- fixes table headers styling
- fixes hours page table styling
- makes the divider line in the dropdown menu extended to the bottom.
> 731 update web logos

- base/static/base/css/uclib.scss
Fixes #731.
- continues the previous fix by including a mobile view.
> fix mobile color hours table

- base/static/base/css/_variables.scss
- base/static/base/css/footer.scss
- base/static/base/css/uclib-search.scss
> update footer color

- base/static/base/css/global.scss
- base/static/base/css/navigation.scss
- base/static/base/css/uclib.scss
- base/templates/base/public_base.html
Fixes #750.
- removes the color of index-lists as per described in issue #750;
- fixes padding on mobile version of navigation menu; *
- fixes the missing alerts. *
*_These were happening due to a mistake in recent updates to branding._
> 750 index listing colors

- README.md
- base/templates/base/public_base.html
Fixes #776
- removes call to missing file
- updates readme instructions for pushing to production following server migration
> fix 404 call and update readme

- intranethome/templates/intranethome/intranet_home_page.html
Fixes #782, Remove links from Loop sidebar
> remove sidebar links

- README.md
- intranethome/templates/intranethome/intranet_home_page.html
Forgot to remove another section of links.
> 782 remove *additional* links from loop sidebar

- dirbrowse/static/dirbrowse/js/law-exams.js
Fixes #804 
- Alters the sorting of law exams to better respect seasons.
> Change Sorting of Past Law Exams

- base/static/base/css/navigation.scss
- base/templates/base/includes/header.html
Add the Kim-Park Program for the Study of the Book page to the navbar.
Fixes #808 
- Adds a Programs section to About in the navbar.
- Adds a link to [Kim-Park Program for the Study of the Book](https://www.lib.uchicago.edu/about/kim-park-program-for-the-study-of-the-book/)
> Add item to navbar SOTB

- base/templates/base/includes/header.html
> move programs sub-section

- public/tests.py
Bring the `idresolve` unit tests back, as per #770.
> bring the `idresolve` tests back

- .dockerignore
- .gitignore
- Dockerfile
- README.md
- Vagrantfile
- dev-docs.txt
- docker-cleanup.sh
- docker-commands.txt
- docker-compose.yml
- docker-setup.sh
- library_website/settings/docker.py
Implements a Docker-based development environment as an alternative to Vagrant, providing faster startup times, better resource efficiency, and improved cross-platform consistency.
- **Docker Compose setup** with PostgreSQL, Redis, and optional Elasticsearch containers
- **Automated setup script** (`./docker-setup.sh`) with help flag support  
- **Cleanup script** (`./docker-cleanup.sh`) for proper environment teardown
- **Docker-specific Django settings** that maintain compatibility with existing `local.py` configurations
- **Updated README.md** positioning Docker as the recommended development approach
- **Consolidated documentation** to eliminate duplication between setup methods
- **Full backward compatibility** - existing Vagrant workflow unchanged
- **Faster development** - …
> Add Docker development environment as alternative to Vagrant
